### ISSUE TITLE
cv2.error: OpenCV(4.8.1) D:\a\opencv-python\opencv-python\opencv\modules\features2d\src\blobdetector.cpp:102: error: (-5:Bad argument) 0<minConvexity<=maxConvexity in function 'cv::SimpleBlobDetectorImpl::validateParameters'

### ISSUE THREAD

**Issue by Travisma2233** [sebastiengilbert73/tutorial_calibrate_stereo_vision#1]
Hello, I encountered the following problem when using the image added in your file for calibration. How should I solve it?
![image](https://github.com/sebastiengilbert73/tutorial_calibrate_stereo_vision/assets/83893812/0cc090b3-3242-4fcc-a298-c2950c7c720d)

**Comment by sebastiengilbert73** [comment]
Thanks for pointing that out.
I assume the behaviour of cv2.SimpleBlobDetector_Params changed. Values of 0 are no longer accepted for the minimum parameter values. I changed them.
Do 
$ git pull origin main
