### ISSUE TITLE
calibration_pattern_xy.csv

### ISSUE THREAD

**Issue by RasoulZardeyni** [sebastiengilbert73/tutorial_calibrate_stereo_vision#2]
Hello, I had a question about what information is stored in file "calibration_pattern_xy.csv" and how I can calculate this information for my project?

**Comment by sebastiengilbert73** [comment]
Hello Rassoul,
This file contains the (x, y) coordinates (in centimeters) of the intersection points in the calibration pattern.

**Comment by RasoulZardeyni** [comment]
Thanks!
